### PR TITLE
Update PDF.js to v2.11.213

### PR DESCRIPTION
**Pull request by robertknight**
Update PDF.js to the latest version. This includes ~2 years worth of updates, including a fix for https://github.com/hypothesis/browser-extension/issues/626, improved text selection (eg. resolves problems in some PDFs where all words would run together), and also modernizes the look and feel of the viewer.

PDFjs v2 11 106

The updated version of PDF.js no longer requires the workaround added in https://github.com/hypothesis/browser-extension/pull/630, so the second commit removes it.

In testing this I found a couple of client issues.

https://github.com/hypothesis/client/issues/3673 (minor - can be fixed after the update)
https://github.com/hypothesis/client/issues/3674 (major - needs to be fixed before or shortly after the update. Only seems to affect a small proportion of annotations in practice)

### CODE REVIEW

**Comment by robertknight** [comment]
In debugging this I found an issue with an implicit assumption in the client's code that the page text as returned by PDF.js's `getTextContent` method exactly matches the `textContent` property of the `.textLayer` div element in the transparent text overlay that PDF.js creates for rendered pages. In my initial debugging it seems that this is no longer the case.

Example page text returned by `getTextContent`:

```
8/25/2020Nils Olav - Wikipediahttps://en.wikipedia.org/wiki/Nils_Olav1/3Sir Nils Olav IIISpeciesKing penguin (Aptenodytes patagonicus)SexMaleBornSir Nils Olav IIIHatchedc. 2008 (age 11–12)Edinburgh, ScotlandResidenceEdinburgh ZooMilitary careerAllegianceNorwayService/branchNorwegian ArmyYears ofservice1972–1987 (first)1987 – after 2008 (second)before 2016 – present (third)[1]RankBrigadier, colonel-in-chief, and mascotUnitHans Majestet Kongens GardeNils OlavBrigadier Sir Nils Olav III is a king penguin whoresides  in Edinburgh  Zoo,  Scotland.  He  is  themascot[2][3][4] and colonel-in-chief of the NorwegianKing's Guard. The name 'Nils Olav' and associatedranks  have  been  passed  down  through  three  kingpenguins since 1972 – the current holder being NilsOlav III.[1][5]Role in the militarySee alsoReferencesExternal linksNorway – whose explorer Roald Amundsen was thefirst  person  to  reach  the  South  Pole  in  1911  –presented Edinburgh Zoo with its first king penguinat its opening in 1913.[6]When  the Norwegian  King's  Guard  visited  theEdinburgh  Military  Tattoo  of  1961  for  a  drilldisplay,[7] a lieutenant named Nils Egelien becameinterested  in  the  zoo's  penguin  colony.  When  theKing's Guard returned to Edinburgh in 1972, Egelienarranged for the regiment to adopt a penguin. Thispenguin  was  named  Nils  Olav  in  honour  of  NilsEgelien and KingOlav V of Norway.[2]Nils Olav was initially given the rank of visekorporal(lance  corporal)  in  the  regiment.  He  has  beenpromoted each time the King's Guard has returnedto the zoo. In 1982 he was made a corporal,  andpromoted to sergeant in 1987.[2]  Nils  Olav  I  diedshortly after his promotion to sergeant in 1987, andhis place was taken by Nils Olav II, a two-year-old near-double. He was promoted in 1993 to the rank ofregimental sergeant major and in 2001 promoted to 'honourable regimental sergeant major'.[2] On 18August 2005, he was appointed as colonel-in-chief of the same regiment.[2][8] The next honour was aknighthood, awarded during a visit by soldiers from the Norwegian King's Guard on 15 August 2008.[9]Coordinates: 55°56′40′′N3°16′20′′WContentsRole in the military
```

`textContent` property of text layer element:

```
8/25/2020 Nils Olav - Wikipediahttps://en.wikipedia.org/wiki/Nils_Olav 1/3Sir Nils Olav IIISpecies King penguin (Aptenodytes patagonicus)Sex MaleBorn Sir Nils Olav IIIHatched c. 2008 (age 11–12)Edinburgh, ScotlandResidence Edinburgh ZooMilitary careerAllegiance  NorwayService/branch Norwegian ArmyYears ofservice1972–1987 (first)1987 – after 2008 (second)before 2016 – present (third)[1]Rank  Brigadier, colonel-in-chief, and mascotUnit Hans Majestet Kongens GardeNils OlavBrigadier Sir Nils Olav III is a king penguin whoresides  in  Edinburgh  Zoo,  Scotland.  He  is  themascot[2][3][4] and colonel-in-chief of the NorwegianKing's Guard. The name 'Nils Olav' and associatedranks  have  been  passed  down  through  three  kingpenguins since 1972 – the current holder being NilsOlav III.[1][5]Role in the militarySee alsoReferencesExternal linksNorway – whose explorer Roald Amundsen was thefirst  person  to  reach  the  South  Pole  in  1911  –presented Edinburgh Zoo with its first king penguinat its opening in 1913.[6]When  the  Norwegian  King's  Guard  visited  theEdinburgh  Military  Tattoo  of  1961  for  a  drilldisplay,[7] a lieutenant named Nils Egelien becameinterested  in  the  zoo's  penguin  colony.  When  theKing's Guard returned to Edinburgh in 1972, Egelienarranged for the regiment to adopt a penguin. Thispenguin  was  named  Nils  Olav  in  honour  of  NilsEgelien and King Olav V of Norway.[2]Nils Olav was initially given the rank of visekorporal(lance  corporal)  in  the  regiment.  He  has  beenpromoted each time the King's Guard has returnedto the zoo. In 1982 he was made a corporal,  andpromoted to sergeant in 1987.[2]  Nils  Olav  I  diedshortly after his promotion to sergeant in 1987, andhis place was taken by Nils Olav II, a two-year-old near-double. He was promoted in 1993 to the rank ofregimental sergeant major and in 2001 promoted to 'honourable regimental sergeant major'.[2] On 18August 2005, he was appointed as colonel-in-chief of the same regiment.[2][8] The next honour was aknighthood, awarded during a visit by soldiers from the Norwegian King's Guard on 15 August 2008.[9]Coordinates: 55°56′40′′N 3°16′20′′WContentsRole in the military
```

Note that the `textContent` property has additional spaces.

**Comment by robertknight** [comment]
Aha. The `getPageTextContent` function [ in the client code](https://github.com/hypothesis/client/blob/47d1704529f52d42c4e8e894147bde2b02b1c0ab/src/annotator/anchoring/pdf.js#L171) mentions that the client strips whitespace-only entries from the output of `pdfPage.getTextContent` in order for the resulting string to match the rendered text layer. However https://github.com/mozilla/pdf.js/commit/af4dc55019efd82cdb002dc25901d6d113406ebe changed the `appendText` method mentioned in the client's comments so that it does create elements in the text layer for whitespace-only items.

The code here needs to be adapted so that the output matches the text layer for both old and new PDF.js versions. I think we should also add some sanity check to verify that this is the case.

**Comment by robertknight** [comment]
Work in progress fixes for anchoring in new PDF.js releases in the client: https://github.com/hypothesis/client/pull/3687.

**Comment by mkdir-washington-edu** [comment]
PDFs for testing here: https://github.com/hypothesis/client/issues/3688

**Comment by robertknight** [comment]
https://github.com/hypothesis/client/pull/3687 fixed the main issue (https://github.com/hypothesis/client/issues/3674) that prevents us shipping a new version of PDF.js. I think we should ship https://github.com/hypothesis/client/pull/3706 first as well to prevent mis-anchoring.

**Comment by robertknight** [comment]
I did a decent amount of testing yesterday with various PDFs and the number of annotations that are misanchored due to https://github.com/hypothesis/client/issues/3705 seems much smaller than I initially thought. We have a solution in progress in https://github.com/hypothesis/client/pull/3743, but I no longer think its essential to ship that change before this update, as long as we ship it soon after.

**Comment by robertknight** [comment]
I've updated PDF.js to the current version (v2.11.213), since this PR was originally opened a month ago. This will make the version the same as [in Via](https://github.com/hypothesis/via/pull/611).

**Review by esanzgar — APPROVED** [review]

**Pull request merged**
