### PR TITLE
QueryFromUrl changes

### PR DESCRIPTION
**Pull request by greebie**
Changes to browser extension to conform with suggested changes in client to accommodate url queries.

See https://github.com/hypothesis/client/pull/254.

### CODE REVIEW

**Comment by robertknight** [comment]
I provided some feedback on the corresponding changes in the client PR at https://github.com/hypothesis/client/pull/254 , once we've got the client changes agreed and merged then the implementation here can be updated to match.

**Comment by robertknight** [comment]
Can you update this to use the latest version of the function for extracting annotation IDs/queries from URLs that was merged into the client branch please.

**Comment by greebie** [comment]
Hi Robert, I did a conformance edit here.  I think it's worth asking whether it's possible to make what's happening here more explicit for the future.  Look forward to your feedback.

**Comment by nickstenning** [comment]
I've [left a comment](https://github.com/hypothesis/bouncer/pull/42#issuecomment-299660909) over on the bouncer PR with an update from us!

**Comment by nickstenning** [comment]
I've followed up [here on the dev list](https://groups.google.com/a/list.hypothes.is/d/msg/dev/sFH-3xmeK8Y/NLIBlgb_BQAJ).

Closing the PR for now. Hope that's ok with you.

**Pull request closed without merging**
